spring:
  application:
    name: wanted-pre-onboarding-backend
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/recruitment_db
    username: root
    password: "@godaehak21"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
